[general]
live_config_reload = true
import = [
    "~/.config/alacritty/themes/themes/dracula.toml"
]

[window]
padding = { x = 0, y = 0 }
opacity = 0.9
blur = true

[scrolling]
history = 100000

[cursor]
style = "Beam"

[font]
size = 12.0
offset = { x = 0, y = 2 }
normal = { family = "Moralerspace Neon NF", style="Regular" }
bold = { family = "Moralerspace Neon NF", style="Bold" }
italic = { family = "Moralerspace Neon NF", style="Italic" }
bold_italic = { family = "Moralerspace Neon NF", style="Bold Italic" }

[terminal]

[terminal.shell]
program = "/usr/local/bin/fish"
args = ["--login", "-l", "-c", "tmux new-session -A -s main || tmux"]

[env]
TERM = "xterm-256color" 		# macOS | Linux


[[keyboard.bindings]]
action = "ToggleViMode"
key = "Space"
mods = "Command|Control"
